tigergraph/ecosys

benchmark/neo4j/README

Added a few commands to the setup.

Setup Update

---

benchmark/tigergraph/README

Added a few commands for setup.

Updated Setup

---

benchmark/tigergraph/README
benchmark/tigergraph/benchmark-graph500.sh
benchmark/tigergraph/benchmark-twitter.sh
benchmark/tigergraph/profile-graph500.sh
benchmark/tigergraph/profile-twitter.sh

- Automated testing for CPU and Memory consumption while running benchmark tests. 
- Reformatted benchmark scripts from single line to multi-line.

test(benchmark): Automated Testing;

---

graph_algorithms/README.algorithms

Found a small error in documentation.

Fix small typo

---

tools/diag/gcollect/README.md
tools/diag/gcollect/src/gcollect/main.go
tools/diag/gcollect/src/logs/logs.go
tools/diag/gcollect/src/tsar/tsar.go
tools/diag/gcollect/src/utils/utils.go

gcollect is a TigerGraph debug tool, which could be used to collect all the debug information that is needed for TigerGraph debugging.

Added gcollect.

---

ldbc_benchmark/tigergraph/queries/business_intelligence/bi_1.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_12.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_15.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_18.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_3.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_4.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_5.gsql
ldbc_benchmark/tigergraph/queries/business_intelligence/bi_9.gsql
ldbc_benchmark/tigergraph/queries/distributed/bi_10.gsql
ldbc_benchmark/tigergraph/queries/distributed/bi_5.gsql
ldbc_benchmark/tigergraph/queries/distributed/bi_6.gsql
ldbc_benchmark/tigergraph/queries/distributed/ic_12.gsql
ldbc_benchmark/tigergraph/queries/distributed/ic_14.gsql
ldbc_benchmark/tigergraph/queries/distributed/ic_5.gsql
ldbc_benchmark/tigergraph/queries/distributed/is_2.gsql
ldbc_benchmark/tigergraph/queries/interactive_complex/ic_11.gsql
ldbc_benchmark/tigergraph/queries/interactive_complex/ic_5.gsql
ldbc_benchmark/tigergraph/queries/interactive_complex/ic_8.gsql
ldbc_benchmark/tigergraph/queries/interactive_complex/ic_9.gsql

Ldbc improve

---

etl/tg-jdbc-driver/README.md

JDBC: added dependency list.

---

etl/tg-jdbc-driver/tg-jdbc-examples/src/main/java/com/tigergraph/jdbc/UpsertQuery.java
etl/tg-jdbc-driver/tg-jdbc-restpp/src/main/java/com/tigergraph/jdbc/driver/QueryParser.java

1. If there are substrings in a query, they should not be tokenized.
2. Fixed issues with integer and float parameters in json.

JDBC: Fixed issue with query tokenization.

---

etl/tg-jdbc-driver/README.md
etl/tg-jdbc-driver/tg-jdbc-common/src/main/java/com/tigergraph/jdbc/Connection.java
etl/tg-jdbc-driver/tg-jdbc-examples/pom.xml
etl/tg-jdbc-driver/tg-jdbc-examples/src/main/java/com/tigergraph/jdbc/ConnectionPool.java
etl/tg-jdbc-driver/tg-jdbc-examples/src/main/java/com/tigergraph/jdbc/GraphQuery.java
etl/tg-jdbc-driver/tg-jdbc-restpp/src/main/java/com/tigergraph/jdbc/RestppConnection.java
etl/tg-jdbc-driver/tg-jdbc-restpp/src/main/java/com/tigergraph/jdbc/driver/QueryParser.java
etl/tg-jdbc-driver/tg-jdbc-restpp/src/test/java/com/tigergraph/jdbc/QueryParserTest.java
etl/tg-jdbc-driver/tg-jdbc-restpp/src/test/resources/endpoint-expected.dat

A request from customers to support https://github.com/brettwooldridge/HikariCP

Added support for third party connection pools.

---

benchmark/arangodb/README
benchmark/arangodb/profile-adb-graph500.sh
benchmark/arangodb/profile-adb-twitter.sh
benchmark/neo4j/README
benchmark/neo4j/profile-neo4j-graph500.sh
benchmark/neo4j/profile-neo4j-twitter.sh

Provide automated profiling script for neo4j testing. Script only provides peak CPU & Mem consumption data for k-hop, wcc, and pr queries.

test(benchmark): Automated Testing for Neo4j;

---

UDF/README.md

Add UDF Library
* INIT UDF library
Examples:
- substring(string str, int b, int e)

init UDF library

---

tools/etl/tg-jdbc-driver/tg-jdbc-restpp/src/main/java/com/tigergraph/jdbc/driver/QueryParser.java
tools/etl/tg-jdbc-driver/tg-jdbc-restpp/src/test/java/com/tigergraph/jdbc/QueryParserTest.java
tools/etl/tg-jdbc-driver/tg-jdbc-restpp/src/test/resources/endpoint-expected.dat

Request from: https://tigergraph.freshdesk.com/a/tickets/12059

Added support for boolean attributes.

---

UDF/README.md

Add more UDF's to the library
+additions
Examples:
* [String Based UDF](#string-based-udf)
* [substring](#substring) - Given a string of text, return a substring from index begin to index end.
* [str_regex_match](#string-regex-match) - Given a string determine if regex matches, return a boolean.
* [substring](#substring) - Given a string of text, return a substring from index begin to index end
* [str_regex_match](#string-regex-match) - Given a string determine if regex matches, return a boolean
* [string_to_string](#string-to-string) -  string_to_string
* [str_len](#str-len) - Given a string count char to get string size
* [str_find](#str-find) - Given a string find a string in a string, and return where it was found (-1 if not found)
* [regex_filter_set](#regex-filter-set) - Given a set …

Add C++ code snippets to UDF library

---

UDF/README.md

Fixed in-page links in README.md
N/A

Fixed in-page links

---

tools/etl/tg-jdbc-driver/README.md
tools/etl/tg-jdbc-driver/tg-jdbc-driver/dependency-reduced-pom.xml
tools/etl/tg-jdbc-driver/tg-jdbc-driver/pom.xml
tools/etl/tg-jdbc-driver/tg-jdbc-restpp/pom.xml
tools/etl/tg-jdbc-driver/tg-jdbc-restpp/src/main/java/com/tigergraph/jdbc/RestppConnection.java

Addressed some FAQ in README.md
Fixed truststore not found with Spark.
Shaded httpclient.jar to prevent version conflict.

Fixed truststore not found with Spark.

---

tools/clients/README.md

Update README.md to inform that the GSQL client 2.6.0 is compatible with GSQL server 2.6.1, noted as `2.6.*`.
Nothing to release.

Update README.md for 2.6.1 release

---

tools/third-party/README.md
tools/third-party/TigerGraph REST API ++.postman_collection.json

Add TigerGraph Postman Collection 
- Add JSON postman collection
- Update Readme in third party folder

add Postman JSON collection

---

tools/keyguard/README

add keyguard

---

demos/vis/streamlit/covid19starterkit.py

Adding  covid-19 starter kit visualization

---

demos/vis/streamlit/covid19starterkit.py

Updated the vis; removed the age data frame display

---

tools/keyguard/README

Ecosys keyguard

---

demos/guru_scripts/docker_notebook/Dockerfile
demos/guru_scripts/docker_notebook/README.md

This way it will be automatically updated when new versions come out.

Switch base image to tigergraph-docker:latest

---

tools/clients/README.md
tools/clients/make_aio_gsql_client.sh
tools/clients/pom.xml
tools/clients/src/main/java/com/tigergraph/client/Driver.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/AutoCompleter.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/Client.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/Driver.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/GsqlCli.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/logging/GsqlClientLogger.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/logging/GsqlPatternConverter.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/util/ConsoleUtils.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/util/HttpReponseOperator.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/util/IOUtils.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/util/RetryableHttpConnection.java
tools/clients/src/main/java/com/tigergraph/v3_0_0/client/util/SystemUtils.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/AutoCompleter.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/Client.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/Driver.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/GsqlCli.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/logging/GsqlClientLogger.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/logging/GsqlPatternConverter.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/util/ConsoleUtils.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/util/HttpReponseOperator.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/util/IOUtils.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/util/RetryableHttpConnection.java
tools/clients/src/main/java/com/tigergraph/v3_0_5/client/util/SystemUtils.java

Update to GSQL Client 3.0.5
Release GSQL Client 3.0.5 in [Bintray](https://bintray.com/tigergraphecosys/tgjars/gsql_client/3.0.5).

Update gsql-client 3.0.5

---

demos/guru_scripts/docker/README.md

Fix a broken link in README for Docker

update broken link

---

sample_code/src/ExprFunctions.hpp
sample_code/src/ExprUtil.hpp

Add some function and struct to udf files, to test if the gsql can download and use these files for query compilation.

GLE-1875 test(gle): modify udf sample files for test;

---

tools/clients/README.md
tools/clients/make_aio_gsql_client.sh
tools/clients/pom.xml
tools/clients/src/main/java/com/tigergraph/client/Driver.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/AutoCompleter.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/Client.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/Driver.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/GsqlCli.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/logging/GsqlClientLogger.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/logging/GsqlPatternConverter.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/util/ConsoleUtils.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/util/HttpResponseOperator.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/util/IOUtils.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/util/RetryableHttpConnection.java
tools/clients/src/main/java/com/tigergraph/v3_1_0/client/util/SystemUtils.java

Update to GSQL Client 3.1.0
Release GSQL Client 3.1.0 in [Bintray](https://bintray.com/tigergraphecosys/tgjars/gsql_client/3.1.0).

Update gsql-client 3.1.0

---

tools/diag/gcollect/README.md
tools/diag/gcollect/src/gcollect/main.go
tools/diag/gcollect/src/utils/utils.go

This PR fixed two issues:
1. Doesn't work properly on clusters. In cluster mode, gcollect will try to copy itself to other nodes, but it assumes the binary is in current working directory, which is not true. Actually the binary is already existed on all the nodes.
2. Remove dest directory without warning. This may lead to data loss. After the fix, gcollect will exit immediately if the dest directory is already existed.

Fixed issue on clusters and do not delete dest dir silenctly.

---

k8s/aks/kustomization.yaml
k8s/base/installer.yaml
k8s/deploy/tigergraph-docker.yaml
k8s/eks/kustomization.yaml
k8s/gke/kustomization.yaml
k8s/gke/storageclass-pd.yaml
k8s/tg

[TTP-1234] fix(k8s): Fix namespace flag issue for tg script;

---

UDF/README.md

Levenshtein distance

---

k8s/base/configmap.yaml
k8s/base/installer.yaml
k8s/base/statefulset.yaml
k8s/tg

K8s enhancement for installer/config/tg

---

k8s/base/service-loadbalancer-gui.yaml

Add session affinity for Graphstudio

Added session affinity for graphstudio

---

k8s/tg

Fix bug causing the docker image version to be set incorrectly

Fix tg version replacement

---

tools/etl/tg-jdbc-driver/tg-jdbc-driver/pom.xml

modify pom.xml

---

tools/etl/tg-jdbc-driver/README.md
tools/etl/tg-jdbc-driver/tg-jdbc-driver/pom.xml
tools/etl/tg-jdbc-driver/tg-jdbc-driver/src/main/java/com/tigergraph/jdbc/restpp/RestppConnection.java

Fix compatibility issue and add exponential backoff.

---

tools/etl/tg-jdbc-driver/README.md
tools/etl/tg-jdbc-driver/tg-jdbc-driver/pom.xml
tools/etl/tg-jdbc-driver/tg-jdbc-driver/src/main/java/com/tigergraph/jdbc/restpp/RestppPreparedStatement.java

Print restpp responses in ERROR logs when there's any error.

---

tools/etl/tg-jdbc-driver/README.md
tools/etl/tg-jdbc-driver/tg-jdbc-driver/pom.xml
tools/etl/tg-jdbc-driver/tg-jdbc-driver/src/main/java/com/tigergraph/jdbc/restpp/RestppPreparedStatement.java

Fix the notEnoughToken error.

---

k8s/README.md

update k8s instructions

---

k8s/README.md
k8s/docs/01-introduction/README.md
k8s/docs/07-reference/configure-tigergraph-cluster-cr-with-yaml-manifests.md

Update the README for K8s Operator

---

demos/guru_scripts/docker/tutorial/4.x/README.md
demos/guru_scripts/docker/tutorial/4.x/script/load.gsql

Optimize md:
1.add cloud portal for docker environment
2.change to S3 data source
3.fix bugs in queries

optimize md

---

demos/guru_scripts/docker/tutorial/4.x/Cypher-Mini-tuotiral.md
demos/guru_scripts/docker/tutorial/4.x/Cypher-Mini-tutorial.md

[QA-7600] Add cypher README.md

---

.gitignore
.idea/.gitignore
.idea/compiler.xml
.idea/ecosys.iml
.idea/encodings.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
demos/guru_scripts/docker/tutorial/4.x/README.md

Doc 2287 gsqlv3 proofreading

---

demos/guru_scripts/docker/tutorial/4.x/VectorSearch.md

[GLE-9951] modify vector tutorial;

---

tutorials/Cypher.md

[GLE-9952](https://graphsql.atlassian.net/browse/GLE-9952) discovered backward compatibility issues in [GLE-9401](https://graphsql.atlassian.net/browse/GLE-9401). We decided to revert the fix in [GLE-9401](https://graphsql.atlassian.net/browse/GLE-9401) as the quickest way to resolve the compatibility issue (the original fix will be applied to a later release).
This PR updates the tutorial so the examples in tutorial can still run successfully
N/A
[GLE-9952]: https://graphsql.atlassian.net/browse/GLE-9952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GLE-9401]: https://graphsql.atlassian.net/browse/GLE-9401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Update Cypher.md after reverting backward-incompatible fix;

---

tutorials/GraphRAG.md
tutorials/graphrag/graphrag-k8s.yml

GML-1990 Add k8s instruction for graphrag
